import React, { useState } from 'react';
import { AlertTriangle, ShieldAlert, ArrowRight, ExternalLink, CheckCircle2, XCircle } from 'lucide-react';
import { InaccuracyItem } from '../types';

interface InaccuraciesTabProps {
  inaccuracies: InaccuracyItem[];
  onSelectRemediationTask?: (taskId: string) => void;
}

export const InaccuraciesTab: React.FC<InaccuraciesTabProps> = ({ inaccuracies = [], onSelectRemediationTask }) => {
  const [severityFilter, setSeverityFilter] = useState<string>('all');

  const safeInaccuracies = inaccuracies || [];

  const filtered = safeInaccuracies.filter((item) => {
    if (severityFilter === 'all') return true;
    return item.impactSeverity === severityFilter;
  });

  return (
    <div className="space-y-6">
      {/* Header Banner */}
      <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <ShieldAlert className="h-5 w-5 text-rose-400" />
            <h3 className="text-base font-bold text-white">AI Search Inaccuracies & Hallucinations</h3>
          </div>
          <p className="text-xs text-slate-400 mt-1">
            Detect false claims, outdated pricing limits, or missing feature capability assertions generated by AI search models.
          </p>
        </div>

        {/* Severity Filter Buttons */}
        <div className="flex items-center gap-2">
          <button
            onClick={() => setSeverityFilter('all')}
            className={`px-3 py-1.5 rounded-lg text-xs font-medium transition ${
              severityFilter === 'all'
                ? 'bg-indigo-600 text-white'
                : 'bg-slate-800 text-slate-400 hover:text-white'
            }`}
          >
            All ({safeInaccuracies.length})
          </button>
          <button
            onClick={() => setSeverityFilter('high')}
            className={`px-3 py-1.5 rounded-lg text-xs font-medium transition ${
              severityFilter === 'high'
                ? 'bg-rose-600 text-white'
                : 'bg-slate-800 text-slate-400 hover:text-white'
            }`}
          >
            High Severity ({safeInaccuracies.filter((i) => i.impactSeverity === 'high').length})
          </button>
          <button
            onClick={() => setSeverityFilter('medium')}
            className={`px-3 py-1.5 rounded-lg text-xs font-medium transition ${
              severityFilter === 'medium'
                ? 'bg-amber-600 text-white'
                : 'bg-slate-800 text-slate-400 hover:text-white'
            }`}
          >
            Medium ({safeInaccuracies.filter((i) => i.impactSeverity === 'medium').length})
          </button>
        </div>
      </div>

      {/* Inaccuracies List */}
      {filtered.length === 0 ? (
        <div className="bg-slate-900/60 border border-slate-800 rounded-xl p-12 text-center text-slate-400 space-y-2">
          <CheckCircle2 className="h-10 w-10 text-emerald-400 mx-auto" />
          <h4 className="text-base font-semibold text-white">No Inaccuracies Found</h4>
          <p className="text-xs text-slate-500">
            All AI search mentions for the selected filter were factually accurate.
          </p>
        </div>
      ) : (
        <div className="grid grid-cols-1 gap-4">
          {filtered.map((item) => (
            <div
              key={item.id}
              className="bg-slate-900/90 border border-slate-800 hover:border-slate-700 rounded-xl p-5 shadow-md transition space-y-4"
            >
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 border-b border-slate-800/80 pb-3">
                <div className="flex items-center gap-2">
                  <span className="px-2.5 py-0.5 rounded-md bg-indigo-500/10 border border-indigo-500/30 text-indigo-300 text-xs font-bold">
                    {item.engine}
                  </span>
                  <span className="text-xs text-slate-400 italic">
                    Query: "{item.queryText}"
                  </span>
                </div>

                <span
                  className={`px-2.5 py-0.5 rounded-full text-[11px] font-semibold border self-start sm:self-auto ${
                    item.impactSeverity === 'high'
                      ? 'bg-rose-500/20 text-rose-300 border-rose-500/40'
                      : item.impactSeverity === 'medium'
                      ? 'bg-amber-500/20 text-amber-300 border-amber-500/40'
                      : 'bg-slate-800 text-slate-300 border-slate-700'
                  }`}
                >
                  {item.impactSeverity.toUpperCase()} IMPACT
                </span>
              </div>

              {/* Claimed Fact vs Actual Fact Comparison Grid */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="bg-rose-950/20 border border-rose-500/20 rounded-lg p-3.5 space-y-1">
                  <div className="flex items-center gap-1.5 text-xs font-semibold text-rose-400">
                    <XCircle className="h-4 w-4 shrink-0" />
                    <span>Claimed False Fact (AI Hallucination)</span>
                  </div>
                  <p className="text-xs text-slate-200 leading-relaxed pt-1">
                    "{item.claimedFact}"
                  </p>
                </div>

                <div className="bg-emerald-950/20 border border-emerald-500/20 rounded-lg p-3.5 space-y-1">
                  <div className="flex items-center gap-1.5 text-xs font-semibold text-emerald-400">
                    <CheckCircle2 className="h-4 w-4 shrink-0" />
                    <span>Verified Actual Fact</span>
                  </div>
                  <p className="text-xs text-slate-200 leading-relaxed pt-1">
                    "{item.actualFact}"
                  </p>
                </div>
              </div>

              {/* Origin Source URL & Remediation Button */}
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pt-2 text-xs">
                {item.sourceOriginUrl ? (
                  <div className="flex items-center gap-1.5 text-slate-400">
                    <span>Suspected Scraped Origin Source:</span>
                    <a
                      href={item.sourceOriginUrl}
                      target="_blank"
                      rel="noreferrer"
                      className="text-indigo-400 hover:text-indigo-300 underline inline-flex items-center gap-1 truncate max-w-xs"
                    >
                      {item.sourceOriginUrl.replace(/^https?:\/\//, '')}
                      <ExternalLink className="h-2.5 w-2.5" />
                    </a>
                  </div>
                ) : (
                  <span className="text-slate-500">Origin Source: Direct LLM Parametric Memory</span>
                )}

                {item.remediationTaskId && onSelectRemediationTask && (
                  <button
                    onClick={() => onSelectRemediationTask(item.remediationTaskId!)}
                    className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-indigo-600/80 hover:bg-indigo-600 text-white font-medium transition text-xs shadow-sm self-start sm:self-auto"
                  >
                    <span>View Remediation Fix</span>
                    <ArrowRight className="h-3.5 w-3.5" />
                  </button>
                )}
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};
